### PR TITLE
Remove unused MagnetarStorage old actions IDs `CU-86dtn6486`

### PR DESCRIPTION
**Pull request by 0xRektora**
chore(`MagnetarStorage`): Removed unused `MAGNETAR_ACTION` constants [`86dtn6486`]

### CODE REVIEW

**Comment by 0xRektora** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/Tapioca-DAO/tapioca-periph/330?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#330** <a href="https://app.graphite.dev/github/pr/Tapioca-DAO/tapioca-periph/330?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#329** <a href="https://app.graphite.dev/github/pr/Tapioca-DAO/tapioca-periph/329?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @0xRektora and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by 0xRektora** [comment]
Task linked: [CU-86dtn6486 Remove unused MagnetarStorage old actions IDs](https://app.clickup.com/t/86dtn6486)

**Review by maarcweiss — APPROVED** [review]
Looks good

**Comment by 0xRektora** [comment]
### Merge activity

* **Jun 23, 1:50 PM EDT**: @0xRektora started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/Tapioca-DAO/tapioca-periph/330).

**Pull request merged**
