### PR TITLE
deadrosez | [H-01] [H-02] `_checkPermitBatchApproval` doesn't always execute permit check CU-86dthwup4

### PR DESCRIPTION
**Pull request by 0xRektora**
fix(`Pearlmit`): Always check approvals & overwrite data regardless of past allowances [`86dthr92u`][`86dthr9a4`]
- Removed `_batchAllowanceCheck()`
- Always checking permit data in `_checkPermitBatchApproval` regardless of past allowances

### CODE REVIEW

**Comment by 0xRektora** [comment]
Task linked: [CU-86dthr8rr deadrosez | [C-01] permitBatchTransferFrom does not lower approvals #9](https://app.clickup.com/t/86dthr8rr)
Task linked: [CU-86dthr92u deadrosez | [H-01] permitBatchApproval allows any arbitrary user to lower anyone's approval #11](https://app.clickup.com/t/86dthr92u)

**Comment by 0xRektora** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/Tapioca-DAO/tapioca-periph/284?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#284** <a href="https://app.graphite.dev/github/pr/Tapioca-DAO/tapioca-periph/284?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#283** <a href="https://app.graphite.dev/github/pr/Tapioca-DAO/tapioca-periph/283?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#282** <a href="https://app.graphite.dev/github/pr/Tapioca-DAO/tapioca-periph/282?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#281** <a href="https://app.graphite.dev/github/pr/Tapioca-DAO/tapioca-periph/281?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#280** <a href="https://app.graphite.dev/github/pr/Tapioca-DAO/tapioca-periph/280?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @0xRektora and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by 0xRektora** [comment]
Task linked: [CU-86dthwup4 [H-02] Any user can extend any approval's deadline. #12](https://app.clickup.com/t/86dthwup4)

**Comment by cryptotechmaker** [comment]
Reviewed

**Review by maarcweiss — APPROVED** [review]
Fixed

**Comment by 0xRektora** [comment]
### Merge activity

* **May 23, 6:11 PM EDT**: @0xRektora started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/Tapioca-DAO/tapioca-periph/284).

**Pull request merged**
