### PR TITLE
deadrosez | [C-01] [C-02] `permitBatchTransferFrom` `CU-86dthr8yh` `CU-86dthr8rr`

### PR DESCRIPTION
**Pull request by 0xRektora**
This PR removes the `permitBatchTransferFrom` function from the `Pearlmit` smart contract.

https://github.com/deadrosesxyz/TapiocaIssues/issues/9
https://github.com/deadrosesxyz/TapiocaIssues/issues/10

### CODE REVIEW

**Comment by 0xRektora** [comment]
Task linked: [CU-86dtgzrat deadrosez | [OOS] ZeroXSwapper contract does not properly enforce swapTarget is 0x/1inch and allows for arbitrary call.](https://app.clickup.com/t/86dtgzrat)
Task linked: [CU-86dthr8rr deadrosez | [C-01] permitBatchTransferFrom does not lower approvals #9](https://app.clickup.com/t/86dthr8rr)

**Comment by 0xRektora** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/Tapioca-DAO/tapioca-periph/283?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#283** <a href="https://app.graphite.dev/github/pr/Tapioca-DAO/tapioca-periph/283?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#282** <a href="https://app.graphite.dev/github/pr/Tapioca-DAO/tapioca-periph/282?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#281** <a href="https://app.graphite.dev/github/pr/Tapioca-DAO/tapioca-periph/281?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#280** <a href="https://app.graphite.dev/github/pr/Tapioca-DAO/tapioca-periph/280?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @0xRektora and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by 0xRektora** [comment]
CU-86dthr8yh

**Comment by 0xRektora** [comment]
Task linked: [CU-86dthr8yh deadrosez | [C-02] allowance check is done on the approval.operator instead of msg.sender #10](https://app.clickup.com/t/86dthr8yh)

**Comment by cryptotechmaker** [comment]
Reviewed

**Comment by 0xRektora** [comment]
### Merge activity

* **May 23, 6:11 PM EDT**: @0xRektora started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/Tapioca-DAO/tapioca-periph/283).

**Pull request merged**
