### PR TITLE
Use Pearlmit on TOB exerciseOption for oTAP approval `CU-86dthzrv6`

### PR DESCRIPTION
**Pull request by 0xRektora**
patch(`Magnetar`): Clear `Pearlmit->oTap` allowance post exercise in `_processExerciseOption()`  [`86dthzrv6`]

### CODE REVIEW

**Comment by 0xRektora** [comment]
Task linked: [CU-86dtjd3m0 deadrosez | [M-05] Magnetar gives an ERC721 approval to TapiocaOptionBroker, when in reality it works with Pearlmit approvals #19](https://app.clickup.com/t/86dtjd3m0)

**Comment by 0xRektora** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/Tapioca-DAO/tapioca-periph/294?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#294** <a href="https://app.graphite.dev/github/pr/Tapioca-DAO/tapioca-periph/294?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#293** <a href="https://app.graphite.dev/github/pr/Tapioca-DAO/tapioca-periph/293?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#292** <a href="https://app.graphite.dev/github/pr/Tapioca-DAO/tapioca-periph/292?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#291** <a href="https://app.graphite.dev/github/pr/Tapioca-DAO/tapioca-periph/291?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#290** <a href="https://app.graphite.dev/github/pr/Tapioca-DAO/tapioca-periph/290?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#285** <a href="https://app.graphite.dev/github/pr/Tapioca-DAO/tapioca-periph/285?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#286** <a href="https://app.graphite.dev/github/pr/Tapioca-DAO/tapioca-periph/286?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#284** <a href="https://app.graphite.dev/github/pr/Tapioca-DAO/tapioca-periph/284?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#283** <a href="https://app.graphite.dev/github/pr/Tapioca-DAO/tapioca-periph/283?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#282** <a href="https://app.graphite.dev/github/pr/Tapioca-DAO/tapioca-periph/282?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#281** <a href="https://app.graphite.dev/github/pr/Tapioca-DAO/tapioca-periph/281?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#280** <a href="https://app.graphite.dev/github/pr/Tapioca-DAO/tapioca-periph/280?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @0xRektora and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by 0xRektora** [comment]
Task linked: [CU-86dthzrv6 Use Pearlmit on TOB exerciseOption for oTAP approval](https://app.clickup.com/t/86dthzrv6)

**Comment by cryptotechmaker** [comment]
Reviewed

**Comment by 0xRektora** [comment]
### Merge activity

* **May 23, 6:11 PM EDT**: @0xRektora started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/Tapioca-DAO/tapioca-periph/294).

**Pull request merged**
