### PR TITLE
deadrosez | [L-02] BaseLeverageExecutor does not verify that the actually swapped amount is the same as amountIn

### PR DESCRIPTION
**Pull request by cryptotechmaker**
patch(0x Swapper): removed 1inch fallback from 0x Swapper [86dtgzrat]
- Removed 1inch support from ZeroXSwapper.sol file as it will be implemented as an internal contract if needed

`GT_CU-86dtgzrat-remove-1inch-0x-swapper`

### CODE REVIEW

**Comment by 0xRektora** [comment]
Task linked: [CU-86dtgzrat deadrosez | [OOS] ZeroXSwapper contract does not properly enforce swapTarget is 0x/1inch and allows for arbitrary call.](https://app.clickup.com/t/86dtgzrat)
Task linked: [CU-86dth3q0e deadrosez | [L-02] BaseLeverageExecutor does not verify that the actually swapped amount is the same as amountIn](https://app.clickup.com/t/86dth3q0e)

**Comment by cryptotechmaker** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/Tapioca-DAO/tapioca-periph/282?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#282** <a href="https://app.graphite.dev/github/pr/Tapioca-DAO/tapioca-periph/282?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#281** <a href="https://app.graphite.dev/github/pr/Tapioca-DAO/tapioca-periph/281?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#280** <a href="https://app.graphite.dev/github/pr/Tapioca-DAO/tapioca-periph/280?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @cryptotechmaker and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by 0xRektora** [comment]
Task linked: [CU-86dtjd3m0 deadrosez | [M-05] Magnetar gives an ERC721 approval to TapiocaOptionBroker, when in reality it works with Pearlmit approvals #19](https://app.clickup.com/t/86dtjd3m0)

**Comment by 0xRektora** [comment]
### Merge activity

* **May 23, 6:11 PM EDT**: @0xRektora started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/Tapioca-DAO/tapioca-periph/282).

**Pull request merged**
