### PR TITLE
deadrosez | [M-05] Magnetar gives an ERC721 approval to TapiocaOptionBroker, when in reality it works with Pearlmit approvals #19 [`CU-86dtjd3m0`]

### PR DESCRIPTION
**Pull request by cryptotechmaker**

### CODE REVIEW

**Comment by 0xRektora** [comment]
Task linked: [CU-86dtjd3ku deadrosez | [M-04] MagnetarOptionModule uses wrong TapiocaOptionLiquidityProvision interface #18](https://app.clickup.com/t/86dtjd3ku)
Task linked: [CU-86dtjd3m0 deadrosez | [M-05] Magnetar gives an ERC721 approval to TapiocaOptionBroker, when in reality it works with Pearlmit approvals #19](https://app.clickup.com/t/86dtjd3m0)

**Comment by cryptotechmaker** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/Tapioca-DAO/tapioca-periph/293?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#293** <a href="https://app.graphite.dev/github/pr/Tapioca-DAO/tapioca-periph/293?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#292** <a href="https://app.graphite.dev/github/pr/Tapioca-DAO/tapioca-periph/292?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#291** <a href="https://app.graphite.dev/github/pr/Tapioca-DAO/tapioca-periph/291?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#290** <a href="https://app.graphite.dev/github/pr/Tapioca-DAO/tapioca-periph/290?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#285** <a href="https://app.graphite.dev/github/pr/Tapioca-DAO/tapioca-periph/285?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#281** <a href="https://app.graphite.dev/github/pr/Tapioca-DAO/tapioca-periph/281?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#282](https://github.com/Tapioca-DAO/tapioca-periph/pull/282) <a href="https://app.graphite.dev/github/pr/Tapioca-DAO/tapioca-periph/282?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#280** <a href="https://app.graphite.dev/github/pr/Tapioca-DAO/tapioca-periph/280?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @cryptotechmaker and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by maarcweiss — APPROVED** [review]
Fixed

**Comment by 0xRektora** [comment]
### Merge activity

* **May 23, 6:11 PM EDT**: @0xRektora started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/Tapioca-DAO/tapioca-periph/293).

**Pull request merged**
