### PR TITLE
Missing conversion of deposited assets to borrow parts before repayment in MagnetarAssetModule #154

### PR DESCRIPTION
**Pull request by cryptotechmaker**

### CODE REVIEW

**Comment by 0xRektora** [comment]
Task linked: [CU-86dt57y18 Missing conversion of deposited assets to borrow parts before repayment in MagnetarAssetModule #154](https://app.clickup.com/t/86dt57y18)

**Comment by cryptotechmaker** [comment]
Merged https://github.com/Tapioca-DAO/tapioca-periph/pull/208/files into this one

**Comment by 0xRektora** [comment]
https://github.com/code-423n4/2024-02-tapioca-findings/issues/154

**Review by 0xRektora — APPROVED** [review]

**Comment by 0xRektora** [comment]
### Merge activity

* **Apr 11, 2:31 PM EDT**: @0xRektora started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/Tapioca-DAO/tapioca-periph/211).

**Pull request merged**
