### PR TITLE
Missing TOB exerciseOption in Magnetar actions [`CU-86dthta77`]

### PR DESCRIPTION
**Pull request by cryptotechmaker**
- Added a new action to `Magnetar`
- Added test
- Update interfaces

### CODE REVIEW

**Comment by 0xRektora** [comment]
Task linked: [CU-86dth3q0e deadrosez | [L-02] BaseLeverageExecutor does not verify that the actually swapped amount is the same as amountIn](https://app.clickup.com/t/86dth3q0e)
Task linked: [CU-86dthta77 Missing TOB exerciseOption in Magnetar actions](https://app.clickup.com/t/86dthta77)

**Comment by cryptotechmaker** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/Tapioca-DAO/tapioca-periph/285?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#285** <a href="https://app.graphite.dev/github/pr/Tapioca-DAO/tapioca-periph/285?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#281** <a href="https://app.graphite.dev/github/pr/Tapioca-DAO/tapioca-periph/281?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#282](https://github.com/Tapioca-DAO/tapioca-periph/pull/282) <a href="https://app.graphite.dev/github/pr/Tapioca-DAO/tapioca-periph/282?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#280** <a href="https://app.graphite.dev/github/pr/Tapioca-DAO/tapioca-periph/280?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `dev`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @cryptotechmaker and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by 0xRektora** [comment]
Task linked: [CU-86dtj597v Reset the allowance after a transfer and add external func to clear it explicitly](https://app.clickup.com/t/86dtj597v)

**Comment by 0xRektora** [comment]
### Merge activity

* **May 23, 6:11 PM EDT**: @0xRektora started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/Tapioca-DAO/tapioca-periph/285).

**Pull request merged**
