### PR TITLE
Rural Amethyst Tapir - All ETH can be stolen during rebalancing for mTOFTs that hold native #69

### PR DESCRIPTION
**Pull request by cryptotechmaker**
### TL;DR

Updates swapETH to swapETHAndCall, and introduces SwapAmount struct in StargateRouter interface.

### What changed?

Changed swapETH function to swapETHAndCall in IStargateRouter. This function now takes a new struct SwapAmount, which specifies the amount to be swapped and the minimum swap amount, and the LZ tx params, along with a payload to send to the destination, replacing individual parameters in the old swapETH function. Also added SwapAmount struct to IStargateRouterBase.

### CODE REVIEW

**Comment by 0xRektora** [comment]
Task linked: [CU-86dt22ggj Rural Amethyst Tapir - All ETH can be stolen during rebalancing for mTOFTs that hold native #69](https://app.clickup.com/t/86dt22ggj)

**Comment by 0xRektora** [comment]
* **#198** <a href="https://app.graphite.dev/github/pr/Tapioca-DAO/tapioca-periph/198?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `c4-02-2024-fixes`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @cryptotechmaker and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by 0xRektora — APPROVED** [review]

**Review by 0xRektora — APPROVED** [review]

**Comment by 0xRektora** [comment]
https://github.com/code-423n4/2024-02-tapioca-findings/issues/69

**Comment by 0xRektora** [comment]
### Merge activity

* **Apr 11, 2:31 PM EDT**: @0xRektora started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/Tapioca-DAO/tapioca-periph/198).

**Review by maarcweiss — COMMENTED** [review]
Seems good to me, `swapETHAndCall` was introduced instead of `swapETH`

**Pull request merged**
